Created the following file: routes(errRouter, homeRouter, indexRouter…
nmunro/CNWeatherProject pull request #7
Opened 2020-09-09 15:57 UTC by SilviaPetruta

Created the following file: routes(errRouter, homeRouter, indexRouter, weatherRouter), 404 page. Added the code for each specific page.

2020-09-09 16:19 UTC, nmunro requested changes
Couple of changes requested, nothing major, just some best practices :)

2020-09-09 16:19 UTC, nmunro commented on silvia/lib/getWeather.js
> +require('dotenv').config();
I'd move this to index.js, just incase other environmental variables are added later, at least then it is in the main part of the code.

2020-09-09 16:19 UTC, nmunro commented on silvia/index.js
> +app.use('/', homeRouter);
Will this interfere with the indexRouter on line 27?

2020-09-10 09:34 UTC, SilviaPetruta commented on silvia/index.js
> +app.use('/', homeRouter);
I have deleted the homeRouter.

2020-09-10 09:37 UTC, SilviaPetruta commented on silvia/lib/getWeather.js
> +require('dotenv').config();
I have tried to move this 2 lines in index.js file, but it is not working, because we need fetch method in getWeather.js file where we have the url  in order to fetch the API.

2020-09-10 10:54 UTC, immy80 approved these changes

2020-09-10 10:58 UTC, immy80 approved these changes
Looks very good!

2020-09-10 12:12 UTC, nmunro commented on silvia/index.js
> +app.use('/', homeRouter);
Awesome!

2020-09-10 12:12 UTC, nmunro commented on silvia/lib/getWeather.js
> +require('dotenv').config();
Ok, I'll investigate this myself a little later, but I will merge this now so it's in main :)

2020-09-10 12:13 UTC, nmunro approved these changes

2020-09-10 12:13 UTC, merged